[package]
name = "typelist"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dev-dependencies]
assert-tokenstreams-eq = "0.1.0"

[dependencies]
itertools = "0.13.0"
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = "2.0.90"
